apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: skinny-sturgeon-go 
  janus-idp.io/tekton: skinny-sturgeon-go
  backstage.io/kubernetes-id: skinny-sturgeon-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: skinny-sturgeon-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  